In [ ]:
!pip install PyMySQL
!pip install peewee

In [ ]:
#  connection on EC2 RDS

import peewee
import pymysql

db = peewee.MySQLDatabase('myproject',
                          user='BB1032',
                          host='localhost',
                          password='IamBB1032',
                          port=5200)

In [4]:
#  connection on localhost

import peewee
import pymysql

db = peewee.MySQLDatabase('myproject',
                          user='root',
                          host='localhost',
                          password='athena1225')

In [8]:

class similarity(peewee.Model):
    product_id_1 = peewee.IntegerField()
    product_id_2 = peewee.IntegerField()
    similar = peewee.FloatField()
    appearence = peewee.FloatField()
    
   
    
    class Meta:
        database = db

In [9]:

def insert_data(df):
    dicts=({'product_id_1': df['product1'][i],
            'product_id_2': df['product2'][i],
            'similar': float(df['similar'][i]),
            'appearence': float(df['appearence'][i]),
            
           } for i in range(df['product1'].count()))
    with db.atomic():
        similarity.insert_many(dicts).execute()

In [1]:

import pandas as pd


file = "D:\\project\\result\\similarity.csv"
df = pd.read_csv(file,sep=',',encoding='utf-8')

In [2]:
df

       Unnamed: 0  product1  product2   similar  appearence
0            7946     37798     38454  0.973203          10
1            8139     23258     45651  0.950664          10
2            7729      6338     11171  0.948294          10
3            7073     36775     37798  0.932518          10
4            3452     14852     47719  0.945022          10
5           14343     34832     49346  0.978120          10
6            3444     29923     61356  0.986785          10
7           18929     15334     15899  0.972041          10
8            6407     47293     79932  0.957686          10
9           19249     29923     47441  0.964745          10
10          20993     47719     53759  0.961209          10
11          10280      6495     34004  0.978359          10
12          23471     41519     50986  0.986166          10
13           7287     23258     49346  0.981248          10
14          12246      6495     76780  0.982567          10
15           7282     37798     47719  0.932314          10
16           3432      7315      7416  0.987600          10
17           4573      6495     54515  0.975461          10
18          14089      6470      8799  0.956041          10
19          10216      6495     31891  0.954811          10
20          21752     11171     32214  0.984877          10
21          10211      6495     16686  0.958373          10
22          24946     45691     53216  0.915385          10
23           1315     42372     47293  0.950849          10
24          18944     10147     23258  0.919253          10
25          10799     42501     53216  0.924641          10
26          14357      6495     44955  0.933321          10
27          10345      7247      7416  0.933530          10
28          12589      5635      6328  0.967524          10
29          19294     26098     29929  0.952887          10
...           ...       ...       ...       ...         ...
26772       26411     11171     32945  0.950561           9
26773       11073     11171     75530  0.963311           9
26774       20707     11804     14111  0.991600           9
26775        9623     47441     67973  0.994616           9
26776       20939     23258     61356  0.967173           9
26777       20981     49346     54395  0.958942           9
26778       14844      9234      9556  0.960573           9
26779        9864      7342      8851  0.966872           9
26780       21167     47719     67781  0.988791           9
26781       24978      6495      8317  0.980226           9
26782        9930     12541     79932  0.973124           9
26783        3322     11171     42236  0.968950           9
26784       25007     73445     75932  0.976065           9
26785       10033     42372     45691  0.965422           9
26786       17899      7342     61356  0.984136           9
26787       21103      6495     54224  0.949923           9
26788       10359     47441     53926  0.970278           9
26789       17905     66856     75932  0.950923           9
26790       17914     32214     67291  0.992756           9
26791       10141     77760     82133  0.993859           9
26792       15951      9556     12176  0.974321           9
26793       21033     53216     77760  0.913842           9
26794       10207      6495     52622  0.940331           9
26795       10231     53216     79932  0.899735           9
26796       20984     12176     13740  0.962489           9
26797       15928      7342     13909  0.954341           9
26798       10285     43976     46931  0.987562           9
26799       10065     50986     77770  0.982285           9
26800       24921      6495     38454  0.975506           9
26801       21548      7342     23258  0.962620          96

[26802 rows x 5 columns]

In [10]:
insert_data(df)